version: '2'
volumes:
      postgres-data:
services:
  postgres:
    image: postgres
    env_file:
      - ./.env
    ports:
      - 5433:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  perp-relayer:
    build: .
    stdin_open: true
    volumes:
      - ./config-files/config1.json:/app/config.json
      - ./logs/relayer.log:/app/logs/relayer.log
    ports:
      - "80:8080"
    tty: true
    restart: on-failure
    environment:
      - FILE_PATH=.
      - FILE_NAME=config.json