version: '2'
services:
  perp-relayer:
    build: .
    stdin_open: true
    volumes:
      - ./config-files/config1.json:/app/config.json
      - ./db/test1.db:/app/test1.db
      - ./logs/relayer.log:/app/logs/relayer.log
    ports:
      - "80:8080"
    tty: true
    restart: on-failure
    environment:
      - FILE_PATH=.
      - FILE_NAME=config.json